
[window]
dimensions = { columns = 120, lines = 40 }
option_as_alt = "None"

[font]
normal = { family = ""MonaSpice Ar NFM" }
size = 12

[keyboard]

bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" }
]

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "open"
post_processing = true
mouse = { enabled = true, mods = "Command" }

[general]
# ln -sf ~/dotfiles/alacritty ~/.config/alacritty

import = [
    "~/.config/alacritty/themes/solarized_dark.toml"
]
