# ln -sf ~/dotfiles/alacritty ~/.config/alacritty

import = [
    "~/.config/alacritty/themes/solarized_dark.toml"
]

[window]
dimensions = { columns = 120, lines = 40 }
option_as_alt = "None"

[font]
normal = { family = "Inconsolata-g for Powerline" }
size = 12

[keyboard]

bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" }
]
