#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BLACK="\033[0;30m"
RED="\033[0;31m"
BLUE="\033[0;34m"
NC="\033[0m"

OVERWRITE=''
ARGS="${1:-}"
if [[ "$ARGS" == '--overwrite' ]]; then
	OVERWRITE='true'
fi

function link { # from, to
	local FROM="$1"
	local TO="$2"

	PERFORM_LINK='true'
	if [[ -e "$HOME/$TO" || -h "$HOME/$TO" ]]; then
		if [[ -z "$OVERWRITE" ]]; then
			echo -e "${RED}File ${BLUE}$HOME/$TO${RED} exists - re-run with ${BLUE}--overwrite${RED} to force overwrite${NC}"
			PERFORM_LINK='false'
		else
			rm -rf "$HOME/$TO"
		fi
	fi

	if [[ "$PERFORM_LINK" == 'true' ]]; then
		echo -e "${BLACK}Linking ${BLUE}$DOTFILES_DIR/$FROM${BLACK} to ${BLUE}$HOME/$TO${BLACK}...${NC}"
		ln -sf "$DOTFILES_DIR/$FROM" "$HOME/$TO"
	fi
}

(
    cd "$DOTFILES_DIR"
    git submodule init && git submodule update
)

link "curlrc" ".curlrc"
link "tmux.conf" ".tmux.conf"
link "vim" ".vim"
link "vimrc" ".vimrc"
link "zshrc" ".zshrc"

echo -e "${BLACK}Done${NC}"
