#!/bin/bash

# Initial machine setup; untested in whole as yet

COMPUTER_NAME="${1:-}"
if [[ -z "$COMPUTER_NAME" ]]; then
	echo "Usage: $0 <computer-name>"
	exit 1
fi

BREW_APPS="htop-osx mtr iftop python terminal-notifier tmux rbenv ruby-build rbenv-bundler rbenv-bundler-ruby-version"
CASK_APPS="0xed 1password alfred backblaze backblaze-downloader battle-net calibre doxie dropbox firefox flux google-chrome gog-galaxy grandperspective hazel intellij-idea-bundled-jdk iterm2 java kaleidoscope little-snitch moneydance moom mumble omnigraffle origin scroll-reverser slack spotify skype steam sublime-text teamspeak-client things transmission virtualbox vmware-fusion7 witch viscosity xbox360-controller-driver"
POST_CASK_INSTALLERS="'/opt/homebrew-cask/Caskroom/backblaze/latest/Backblaze Installer.app' '/opt/homebrew-cask/Caskroom/battle-net/latest/Battle.net-Setup-enUS.app'"

# Hack oddities that aren't in cask - HWMonitor, DPCIManager, KextBeast


## Machine name ############################################################

sudo scutil --set ComputerName "$COMPUTER_NAME"
sudo scutil --set HostName "$COMPUTER_NAME"
sudo scutil --set LocalHostName "$COMPUTER_NAME"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$COMPUTER_NAME"


## Dot files ###############################################################

git clone git@github.com:jshiell/oh-my-zsh.git ~/.oh-my-zsh
git clone https://github.com/zsh-users/antigen.git ~/.antigen
git clone git@github.com:jshiell/dotfiles.git ~/dotfile

~/dotfiles/link

## Brew & apps #############################################################

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install git 
brew update

brew update
brew tap caskroom/versions

for APP in ${BREW_APPS}; do
    brew install "$APP"
done

for APP in ${CASK_APPS}; do
    brew cask install --appdir=/Applications --prefpanedir=/Library/PreferencePanes "$APP"
done
for INSTALLER in ${POST_CASK_INSTALLERS}; do
    open $INSTALLER
done 

brew cleanup


## Extra toys

pip install powerline-status

git clone https://github.com/powerline/fonts $TMPDIR/fonts
pushd $TMPDIR/fonts >/dev/null
./install.sh
popd >/dev/null


## General settings ########################################################

# Turn on firewall; disallow signed software from making external requests without confirmation; activate stealth mode
sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
sudo defaults write /Library/Preferences/com.apple.alf allowsignedenabled -bool false
sudo defaults write /Library/Preferences/com.apple.alf stealthenabled -bool true

# Set standby delay to 30m
sudo pmset -a standbydelay 7200

# Disable boot SFX
sudo nvram SystemAudioVolume=" "

# Default save panel is expanded
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Default to saving to disk
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Save screenshots as PNGs
defaults write com.apple.screencapture type -string "png"

# Enable HiDPI modes
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

# Check for updates daily
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Ask for password 10s after screensaver starts
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 10

# Show extended host info on login (click the time)
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Full keyboard access
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Search current directory by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Don't create bloody .DS_Store files on network drives
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Default to column views in Finder
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# Allow AirDrop over ethernet
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Die Dashboard, die
defaults write com.apple.dashboard mcx-disabled -bool true
defaults write com.apple.dock dashboard-in-overlay -bool true

# Autohide the Dock
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide -bool true

# We're not in Kansas
defaults write NSGlobalDomain AppleLanguages -array "en-GB" "en"
defaults write NSGlobalDomain AppleLocale -string "en_GB"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
defaults write NSGlobalDomain AppleMetricUnits -bool true

# Set the timezone; see `sudo systemsetup -listtimezones` for other values
sudo systemsetup -settimezone "Europe/London" > /dev/null

# Clean up launch services duplicates (Open With...)
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# Don't open 'safe' files after downloading
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

# Turn on developer menu/inspector
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

# Hide Time Machine icon
for domain in ~/Library/Preferences/ByHost/com.apple.systemuiserver.*; do
    defaults write "${domain}" dontAutoLoad -array \
        "/System/Library/CoreServices/Menu Extras/TimeMachine.menu"
done

# Disable local TM snapshots
sudo tmutil disablelocal

# Don't ask to backup new volumes
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

## SSDs ####################################################################

# Disable the sudden motion sensor
sudo pmset -a sms 0 

# Disable hibernation
sudo pmset -a hibernatemode 0

# Remove the sleep image and create a read-only file in its place
sudo rm /private/var/vm/sleepimage
sudo touch /private/var/vm/sleepimage
sudo chflags uchg /private/var/vm/sleepimage

# Disabled Gamed
sudo defaults write /System/Library/LaunchAgents/com.apple.gamed disabled -bool true
launchctl unload -w /System/Library/LaunchAgents/com.apple.gamed.plist

